export const LOADING = 'LOADING';
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';

export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_ALL_MEMBERSHIPS_REQUEST = 'GET_ALL_MEMBERSHIPS_REQUEST';
export const GET_ALL_MEMBERSHIPS_SUCCESS = 'GET_ALL_MEMBERSHIPS_SUCCESS';
export const MEMBERSHIP_ADD_REQUEST = 'MEMBERSHIP_ADD_REQUEST';
export const MEMBERSHIP_UPDATE_REQUEST = 'MEMBERSHIP_UPDATE_REQUEST';
export const MEMBERSHIP_DELETE_REQUEST = 'MEMBERSHIP_DELETE_REQUEST';